### ISSUE TITLE
SSL verification fail on fedora23 installation against jenkins

### ISSUE THREAD

**Issue by todoleza** [RHQE/platform-ci#4]
internal old and new CA certificates are installed in global cert storage available for rest of the system
`~/r/p/MVP ❯❯❯ ./jenkins-jobs.sh test`

```
+ upgrade_jjb
+ which pip
/usr/bin/pip
+ pip install --user --upgrade pip
Requirement already up-to-date: pip in /home/todolezafed/.local/lib/python2.7/site-packages
+ pip install --user --upgrade jenkins-job-builder==1.4.0
Requirement already up-to-date: jenkins-job-builder==1.4.0 in /home/todolezafed/.local/lib/python2.7/site-packages
Requirement already up-to-date: pbr<2.0,>=0.8.2 in /home/todolezafed/.local/lib/python2.7/site-packages (from jenkins-job-builder==1.4.0)
Requirement already up-to-date: python-jenkins>=0.4.8 in /home/todolezafed/.local/lib/python2.7/site-packages (from jenkins-job-builder==1.4.0)
Requirement already up-to-date: six>=1.5.2 in /usr/lib/python2.7/site-packages (from jenkins-job-builder==1.4.0)
Requirement already up-to-date: PyYAML in /usr/lib64/python2.7/site-packages (from jenkins-job-builder==1.4.0)
Requirement already up-to-date: ordereddict in /home/todolezafed/.local/lib/python2.7/site-packages (from jenkins-job-builder==1.4.0)
Requirement already up-to-date: multi-key-dict in /home/todolezafed/.local/lib/python2.7/site-packages (from python-jenkins>=0.4.8->jenkins-job-builder==1.4.0)
+ pip install --user --upgrade --index-url=http://ci-ops-jenkins-update-site.rhev-ci-vms.eng.rdu2.redhat.com/packages/simple --trusted-host ci-ops-jenkins-update-site.rhev-ci-vms.eng.rdu2.redhat.com jenkins-ci-sidekick
Requirement already up-to-date: jenkins-ci-sidekick in /home/todolezafed/.local/lib/python2.7/site-packages
Requirement already up-to-date: python-jenkins in /home/todolezafed/.local/lib/python2.7/site-packages (from jenkins-ci-sidekick)
Requirement already up-to-date: pbr<2.0,>=0.8.2 in /home/todolezafed/.local/lib/python2.7/site-packages (from python-jenkins->jenkins-ci-sidekick)
Requirement already up-to-date: multi-key-dict in /home/todolezafed/.local/lib/python2.7/site-packages (from python-jenkins->jenkins-ci-sidekick)
Requirement already up-to-date: six>=1.3.0 in /usr/lib/python2.7/site-packages (from python-jenkins->jenkins-ci-sidekick)
+ jenkins-jobs --ignore-cache --conf config.ini test .
/home/todolezafed/.local/lib/python2.7/site-packages/jenkins/__init__.py:530: DeprecationWarning: get_plugins_info() is deprecated, use get_plugins()
  DeprecationWarning)
Traceback (most recent call last):
  File "/home/todolezafed/.local/bin/jenkins-jobs", line 11, in <module>
    sys.exit(main())
  File "/home/todolezafed/.local/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 172, in main
    execute(options, config)
  File "/home/todolezafed/.local/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 338, in execute
    output=options.output_dir)
  File "/home/todolezafed/.local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 315, in update_job
    self.load_files(input_fn)
  File "/home/todolezafed/.local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 225, in load_files
    self.parser = YamlParser(self.global_config, self.plugins_list)
  File "/home/todolezafed/.local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 221, in plugins_list
    self._plugins_list = self.jenkins.get_plugins_info()
  File "/home/todolezafed/.local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 185, in get_plugins_info
    raise e
jenkins.JenkinsException: Error in request: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
INFO:jenkins_jobs.builder:Cache saved
```

same output goes for `./jenkins-jobs.sh update`

**Comment by lulinqing** [comment]
It's an universal issue when people accessing RH service via CLI without a proper cert installed locally. I've seen quite a few guys seeing the same problem on their laotop.
Solution here: https://docs.engineering.redhat.com/display/CI/Jenkins+CLI+Authentication
And I'll add this link to MVP readme.
Thanks!

**Comment by cmoulliard** [comment]
Do we have to import the 2 certificates on Mac OS using the application Key Chain Access ? 

FYI : the link to install the first certificate "Red Hat IS CA" is not correct - https://password.corp.redhat.com/newca.crt
